linters:
  disable-all: true
  enable:
    - goimports
    - govet
    - misspell
    - revive
    - goconst
    - forbidigo
    - predeclared
linters-settings:
  revive:
    rules:
      - name: confusing-naming
        disabled: true
      - name: exported
        disabled: false
  goconst:
    min-len: 2
    min-occurrences: 10
    match-constant: true
    ignore-strings: "metadata.+"
  forbidigo:
    forbid:
      - p: ^fmt\.Print.*$
        msg: "No format prints, please testing or logrus packages"
run:
  tests: false
  timeout: 10m
issues:
  exclude-files:
    - ^*\.yaml$
    - ^*\.yml$
