---
name: Compare Rancher tag
description: "Compares the latest Rancher tag for specified release lines with cached values"
inputs:
  cached-tag-v211:
    required: true
  cached-tag-v210:
    required: true
  cached-tag-v29:
    required: true
  latest-tag-v211:
    required: true
  latest-tag-v210:
    required: true
  latest-tag-v29:
    required: true
runs:
  using: composite
  steps:
    - run: |
        for RELEASE_LINE in v211 v210 v29; do
          if [[ "$RELEASE_LINE" = "v211" ]]; then
            TAG_INPUT="${{ inputs.latest-tag-v211 }}"
            CACHED_TAG="${{ inputs.cached-tag-v211 }}"
          elif [[ "$RELEASE_LINE" = "v210" ]]; then
            TAG_INPUT="${{ inputs.latest-tag-v210 }}"
            CACHED_TAG="${{ inputs.cached-tag-v210 }}"
          elif [[ "$RELEASE_LINE" = "v29" ]]; then
            TAG_INPUT="${{ inputs.latest-tag-v29 }}"
            CACHED_TAG="${{ inputs.cached-tag-v29 }}"
          fi

          echo "Cached Rancher tag for $RELEASE_LINE: $CACHED_TAG"
          echo "Latest Rancher tag for $RELEASE_LINE: $TAG_INPUT"

          if [ "$CACHED_TAG" != "$TAG_INPUT" ]; then
            echo "New tag for $RELEASE_LINE: $TAG_INPUT"
            echo "IS_TAG_NEW_$RELEASE_LINE=true" >> $GITHUB_ENV
          else
            echo "No new tag found yet for $RELEASE_LINE..."
            echo "IS_TAG_NEW_$RELEASE_LINE=false" >> $GITHUB_ENV
          fi
        done
      shell: bash
