---
name: Check Rancher Tag

on:
  schedule:
    - cron: "0 */4 * * 1-5"
  workflow_dispatch:

jobs:
  check-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      latest_tag_v211: ${{ steps.check-rancher-tag.outputs.LATEST_TAG_v211 }}
      latest_tag_v210: ${{ steps.check-rancher-tag.outputs.LATEST_TAG_v210 }}
      latest_tag_v29: ${{ steps.check-rancher-tag.outputs.LATEST_TAG_v29 }}
      is_tag_new_v211: ${{ steps.check-rancher-tag.outputs.IS_TAG_NEW_v211 }}
      is_tag_new_v210: ${{ steps.check-rancher-tag.outputs.IS_TAG_NEW_v210 }}
      is_tag_new_v29: ${{ steps.check-rancher-tag.outputs.IS_TAG_NEW_v29 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set test tag for v2.11
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "LATEST_TAG_v211=v2.11.3-alpha2" >> $GITHUB_ENV
          echo "IS_TAG_NEW_v211=true" >> $GITHUB_ENV

      - name: Cache prior Rancher tag
        id: cache
        uses: actions/cache@v4
        with:
          path: tag
          key: rancher-tag

      - name: Get latest Rancher tag
        id: get-latest-tag
        uses: ./.github/actions/get-latest-rancher-tag
        with:
          release_lines: "v2.11 v2.10 v2.9"
          prime_artifacts_path: ${{ secrets.PRIME_ARTIFACTS_PATH }}

      - name: Check for new Rancher tag
        id: check-rancher-tag
        uses: ./.github/actions/check-rancher-tag
        with:
          latest-tag-v211: ${{ env.LATEST_TAG_v211 }}
          latest-tag-v210: ${{ env.LATEST_TAG_v210 }}
          latest-tag-v29: ${{ env.LATEST_TAG_v29 }}

      - name: v2.11 - Write new tag to file
        if: ${{ steps.check-rancher-tag.outputs.IS_TAG_NEW_v211 == 'true' }}
        run: |
          mkdir -p tag
          echo "${{ env.LATEST_TAG_v211 }}" > tag/tag_v211.txt

      - name: v2.11 - Cache updated Rancher tag
        if: ${{ steps.check-rancher-tag.outputs.IS_TAG_NEW_v211 == 'true' }}
        uses: actions/cache@v4
        with:
          path: tag/tag_v211.txt
          key: rancher-tag-v211
          restore-keys: |
            rancher-tag

      - name: v2.10 - Write new tag to file
        if: ${{ steps.check-rancher-tag.outputs.IS_TAG_NEW_v210 == 'true' }}
        run: |
          mkdir -p tag
          echo "${{ env.LATEST_TAG_v210 }}" > tag/tag_v210.txt

      - name: v2.10 - Cache updated Rancher tag
        if: ${{ steps.check-rancher-tag.outputs.IS_TAG_NEW_v210 == 'true' }}
        uses: actions/cache@v4
        with:
          path: tag/tag_v210.txt
          key: rancher-tag-v210
          restore-keys: |
            rancher-tag

      - name: v2.9 - Write new tag to file
        if: ${{ steps.check-rancher-tag.outputs.IS_TAG_NEW_v29 == 'true' }}
        run: |
          mkdir -p tag
          echo "${{ env.LATEST_TAG_v29 }}" > tag/tag_v29.txt

      - name: v2.9 - Cache updated Rancher tag
        if: ${{ steps.check-rancher-tag.outputs.IS_TAG_NEW_v29 == 'true' }}
        uses: actions/cache@v4
        with:
          path: tag/tag_v29.txt
          key: rancher-tag-v29
          restore-keys: |
            rancher-tag

  trigger-tests-v211:
    needs: check-latest-tag
    if: ${{ needs.check-latest-tag.outputs.is_tag_new_v211 == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow:
          - sanity-test.yaml
          - sanity-upgrade-test.yaml
          - proxy-test.yaml
          - proxy-upgrade-test.yaml
          - registry-test.yaml
          - airgap-test.yaml
          - airgap-upgrade-test.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger workflow dispatch for ${{ matrix.workflow }}
        uses: ./.github/actions/dispatch-workflow
        with:
          workflow: ${{ matrix.workflow }}
          tag: ${{ needs.check-latest-tag.outputs.latest_tag_v211 }}

  trigger-tests-v210:
    needs: check-latest-tag
    if: ${{ needs.check-latest-tag.outputs.is_tag_new_v210 == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow:
          - sanity-test.yaml
          - sanity-upgrade-test.yaml
          - proxy-test.yaml
          - proxy-upgrade-test.yaml
          - registry-test.yaml
          - airgap-test.yaml
          - airgap-upgrade-test.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger workflow dispatch for ${{ matrix.workflow }}
        uses: ./.github/actions/dispatch-workflow
        with:
          workflow: ${{ matrix.workflow }}
          tag: ${{ needs.check-latest-tag.outputs.latest_tag_v210 }}

  trigger-tests-v29:
    needs: check-latest-tag
    if: ${{ needs.check-latest-tag.outputs.is_tag_new_v29 == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow:
          - sanity-test.yaml
          - sanity-upgrade-test.yaml
          - proxy-test.yaml
          - proxy-upgrade-test.yaml
          - registry-test.yaml
          - airgap-test.yaml
          - airgap-upgrade-test.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger workflow dispatch for ${{ matrix.workflow }}
        uses: ./.github/actions/dispatch-workflow
        with:
          workflow: ${{ matrix.workflow }}
          tag: ${{ needs.check-latest-tag.outputs.latest_tag_v29 }}