---
name: Check Rancher Tag

on:
  schedule:
    - cron: "0 16,20 * * 1-5"
    - cron: "0 0 * * 2-6"
  workflow_dispatch:

jobs:
  check-latest-rancher-tag:
    runs-on: ubuntu-latest
    outputs:
      latest_tag_v212: ${{ steps.get-latest-tag.outputs.latest_tag_v212 }}
      latest_tag_v211: ${{ steps.get-latest-tag.outputs.latest_tag_v211 }}
      latest_tag_v210: ${{ steps.get-latest-tag.outputs.latest_tag_v210 }}
      latest_tag_v29: ${{ steps.get-latest-tag.outputs.latest_tag_v29 }}
      is_tag_new_v212: ${{ steps.compare-rancher-tag.outputs.is_tag_new_v212 }}
      is_tag_new_v211: ${{ steps.compare-rancher-tag.outputs.is_tag_new_v211 }}
      is_tag_new_v210: ${{ steps.compare-rancher-tag.outputs.is_tag_new_v210 }}
      is_tag_new_v29: ${{ steps.compare-rancher-tag.outputs.is_tag_new_v29 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Rancher tag cache
        uses: actions/cache@v4
        with:
          path: tag
          key: rancher-tag-cache

      - name: Get latest Rancher tag
        id: get-latest-tag
        uses: ./.github/actions/get-latest-rancher-tag
        with:
          release_lines: "v2.12 v2.11 v2.10 v2.9"
          prime_artifacts_path: ${{ secrets.PRIME_ARTIFACTS_PATH }}

      - name: Read cached Rancher tags
        id: read-cached-tags
        run: |
          echo "CACHED_TAG_v212=$(cat tag/tag_v212.txt 2>/dev/null || echo '')" >> $GITHUB_ENV
          echo "CACHED_TAG_v211=$(cat tag/tag_v211.txt 2>/dev/null || echo '')" >> $GITHUB_ENV
          echo "CACHED_TAG_v210=$(cat tag/tag_v210.txt 2>/dev/null || echo '')" >> $GITHUB_ENV
          echo "CACHED_TAG_v29=$(cat tag/tag_v29.txt 2>/dev/null || echo '')" >> $GITHUB_ENV

      - name: Compare latest Rancher tag against cached tag
        id: compare-rancher-tag
        uses: ./.github/actions/compare-rancher-tag
        with:
          cached-tag-v212: ${{ env.CACHED_TAG_v212 }}
          cached-tag-v211: ${{ env.CACHED_TAG_v211 }}
          cached-tag-v210: ${{ env.CACHED_TAG_v210 }}
          cached-tag-v29: ${{ env.CACHED_TAG_v29 }}
          latest-tag-v212: ${{ steps.get-latest-tag.outputs.latest_tag_v212 }}
          latest-tag-v211: ${{ steps.get-latest-tag.outputs.latest_tag_v211 }}
          latest-tag-v210: ${{ steps.get-latest-tag.outputs.latest_tag_v210 }}
          latest-tag-v29: ${{ steps.get-latest-tag.outputs.latest_tag_v29 }}

      - name: v2.12 - Write latest tag to file
        run: |
          mkdir -p tag
          echo "${{ steps.get-latest-tag.outputs.latest_tag_v212 }}" > tag/tag_v212.txt

      - name: v2.11 - Write latest tag to file
        run: |
          mkdir -p tag
          echo "${{ steps.get-latest-tag.outputs.latest_tag_v211 }}" > tag/tag_v211.txt

      - name: v2.10 - Write latest tag to file
        run: |
          mkdir -p tag
          echo "${{ steps.get-latest-tag.outputs.latest_tag_v210 }}" > tag/tag_v210.txt

      - name: v2.9 - Write latest tag to file
        run: |
          mkdir -p tag
          echo "${{ steps.get-latest-tag.outputs.latest_tag_v29 }}" > tag/tag_v29.txt

      - name: Save Rancher tag cache
        uses: actions/cache@v4
        with:
          path: tag
          key: rancher-tag-cache

  set-latest-chart-version:
    needs: check-latest-rancher-tag
    runs-on: ubuntu-latest
    outputs:
      chart_version_v212: ${{ steps.set-latest-chart-version.outputs.chart_version_v212 }}
      chart_version_v211: ${{ steps.set-latest-chart-version.outputs.chart_version_v211 }}
      chart_version_v210: ${{ steps.set-latest-chart-version.outputs.chart_version_v210 }}
      chart_version_v29: ${{ steps.set-latest-chart-version.outputs.chart_version_v29 }}

    steps:
      - name: Chart versions
        id: set-latest-chart-version
        run: |
          CHART_V212="${{ needs.check-latest-rancher-tag.outputs.latest_tag_v212 }}"
          CHART_V211="${{ needs.check-latest-rancher-tag.outputs.latest_tag_v211 }}"
          CHART_V210="${{ needs.check-latest-rancher-tag.outputs.latest_tag_v210 }}"
          CHART_V29="${{ needs.check-latest-rancher-tag.outputs.latest_tag_v29 }}"

          echo "chart_version_v212=${CHART_V212#v}" >> $GITHUB_OUTPUT
          echo "chart_version_v211=${CHART_V211#v}" >> $GITHUB_OUTPUT
          echo "chart_version_v210=${CHART_V210#v}" >> $GITHUB_OUTPUT
          echo "chart_version_v29=${CHART_V29#v}" >> $GITHUB_OUTPUT

  trigger-tests-v212:
    needs: [check-latest-rancher-tag, set-latest-chart-version]
    if: ${{ needs.check-latest-rancher-tag.outputs.is_tag_new_v212 == 'true' }}
    uses: ./.github/workflows/dispatch-workflows.yaml
    with:
      rancher_version: ${{ needs.check-latest-rancher-tag.outputs.latest_tag_v212 }}
      rancher_chart_version: ${{ needs.set-latest-chart-version.outputs.chart_version_v212 }}
  
  trigger-tests-v211:
    needs: [check-latest-rancher-tag, set-latest-chart-version]
    if: ${{ needs.check-latest-rancher-tag.outputs.is_tag_new_v211 == 'true' }}
    uses: ./.github/workflows/dispatch-workflows.yaml
    with:
      rancher_version: ${{ needs.check-latest-rancher-tag.outputs.latest_tag_v211 }}
      rancher_chart_version: ${{ needs.set-latest-chart-version.outputs.chart_version_v211 }}

  trigger-tests-v210:
    needs: [check-latest-rancher-tag, set-latest-chart-version]
    if: ${{ needs.check-latest-rancher-tag.outputs.is_tag_new_v210 == 'true' }}
    uses: ./.github/workflows/dispatch-workflows.yaml
    with:
      rancher_version: ${{ needs.check-latest-rancher-tag.outputs.latest_tag_v210 }}
      rancher_chart_version: ${{ needs.set-latest-chart-version.outputs.chart_version_v210 }}

  trigger-tests-v29:
    needs: [check-latest-rancher-tag, set-latest-chart-version]
    if: ${{ needs.check-latest-rancher-tag.outputs.is_tag_new_v29 == 'true' }}
    uses: ./.github/workflows/dispatch-workflows.yaml
    with:
      rancher_version: ${{ needs.check-latest-rancher-tag.outputs.latest_tag_v29 }}
      rancher_chart_version: ${{ needs.set-latest-chart-version.outputs.chart_version_v29 }}