name: Verify Changes

on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  verify-changes:
    name: verify-changes
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'

      - name: Go Version
        run: go version

      - name: Generate Golang
        run: |
          export PATH=$PATH:/home/runner/go/bin/
      
      - name: Verify Go Mod
        run: ./.github/scripts/check-go-mod.sh

      - name: Build Packages
        run: ./.github/scripts/build-packages.sh

      - name: Golangci Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.1
          skip-cache: true